# Generated by Django 4.2.6 on 2023-10-28 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_stripe_charge_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16)),
                ('amount', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('remaining_coupon', models.IntegerField(default=1)),
            ],
        ),
    ]
