# Generated by Django 4.2.6 on 2023-10-27 11:43

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pics',
            field=models.ImageField(default='accounts/blank_avatar.png', upload_to=accounts.models.upload_image_path),
        ),
    ]
